[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "14"

[build.processing]
  # Add any build processing options here

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"