[build]
  # The command that Netlify will use to build your site
  command = "npm run build"

  # Directory to deploy
  publish = ".next"

[build.environment]
  # Environment variables for the build process
  NODE_VERSION = "16" # or the version of Node.js you are using

[[redirects]]
  # Redirects configuration (if needed)
  from = "/*"
  to = "/index.html"
  status = 200
